competition: "numerai"
model_params:
  max_depth: 6
  learning_rate: 0.000123
  l2: 0.1
  n_estimators: 3000
  tree_method: "auto"
  early_stopping_rounds: 10
filename: "xgboost_numerai"
key: "xgboost_numerai"
get_current_data: True
local_data: "inputs/numerai/numerai_dataset.zip"
credentials:
  numerai_public_id: ""
  numerai_secret_key: ""
  user: ""
  password: ""
  bucket: ""
