{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "airflow.serviceAccountName" . }}
  labels:
{{ include "airflow.labels" . | indent 4 }}
{{- end -}}
