name: GoogleQA Bert Fine-tuning with TPUs
data_params:
  train_path: "inputs/google_qa/train-folds.csv"
  test_path: "inputs/google_qa/test.csv"
  submission_path: "inputs/google_qa"
  max_len: 512
model_params:
  model_dir: "trained_models"
training_params:
  train_folds: [0, 1, 2]
  val_folds: [3, 4]
  epochs: 50
  train_batch_size: 64
  test_batch_size: 32
