name: IMDB Sentiment Classification
data_params:
  train_path: "inputs/imdb/train-folds.csv"
  test_path: "inputs/imdb/train-folds.csv"
  submission_path: "inputs/imdb"
  max_len: 512
model_params:
  model_dir: "trained_models"
training_params:
  train_folds: [0]
  val_folds: [4]
  epochs: 12
  train_batch_size: 8
  test_batch_size: 4
